name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from package file
        id: extract_version
        run: |
          VERSION=$(grep -m 1 '"version"' package.json | grep -oP '(?<="version": ")[^"]+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . -t harshadbirajdar/mongo-backup-s3:${{ env.VERSION }} -t harshadbirajdar/mongo-backup-s3:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push harshadbirajdar/mongo-backup-s3:${{ env.VERSION }}
          docker push harshadbirajdar/mongo-backup-s3:latest
